services:
  smartHome:
    build:
      context: ../
      dockerfile: docker/Dockerfile.controlUnit
    ports:
      - "1600:1600"
    environment:
      - CLUSTER_IP=smartHome
      - CLUSTER_PORT=1600
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome

  sensors_garden:
    build:
      context: ../
      dockerfile: docker/Dockerfile.sensors
    environment:
      - CLUSTER_IP=sensors_garden
      - CLUSTER_PORT=2551
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome

  sensors_groundFloor:
    build:
      context: ../
      dockerfile: docker/Dockerfile.sensors
    environment:
      - CLUSTER_IP=sensors_groundFloor
      - CLUSTER_PORT=2552
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome

  sensors_upperFloor:
    build:
      context: ../
      dockerfile: docker/Dockerfile.sensors
    environment:
      - CLUSTER_IP=sensors_upperFloor
      - CLUSTER_PORT=2553
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome

  keypad:
    build:
      context: ../
      dockerfile: docker/Dockerfile.keypad
    environment:
      - CLUSTER_IP=keypad
      - CLUSTER_PORT=2554
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome

  alarm:
    build:
      context: ../
      dockerfile: docker/Dockerfile.alarm
    environment:
      - CLUSTER_IP=alarm
      - CLUSTER_PORT=2555
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome