services:
  smarthome:
    build:
      context: ../
      dockerfile: docker/Dockerfile.controlUnit
    ports:
      - "1600:1600"
    environment:
      - CLUSTER_IP=smarthome
      - CLUSTER_PORT=1600
      - SMARTHOME_PORT_1600_TCP_ADDR=smarthome

  sensors:
    build:
      context: ../
      dockerfile: docker/Dockerfile.sensors
    environment:
      - CLUSTER_IP=sensors
      - CLUSTER_PORT=2551
      - SMARTHOME_PORT_1600_TCP_ADDR=smarthome

  keypad:
    build:
      context: ../
      dockerfile: docker/Dockerfile.keypad
    stdin_open: true
    tty: true
    environment:
      - CLUSTER_IP=keypad
      - CLUSTER_PORT=2552
      - SMARTHOME_PORT_1600_TCP_ADDR=smarthome

  alarm:
    build:
      context: ../
      dockerfile: docker/Dockerfile.alarm
    environment:
      - CLUSTER_IP=alarm
      - CLUSTER_PORT=2553
      - SMARTHOME_PORT_1600_TCP_ADDR=smarthome