services:
  smartHome:
    build:
      context: ../
      dockerfile: docker/Dockerfile.controlUnit
    ports:
      - "1600:1600"
    environment:
      - CLUSTER_IP=smartHome
      - CLUSTER_PORT=1600
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome

  sensors:
    build:
      context: ../
      dockerfile: docker/Dockerfile.sensors
    environment:
      - CLUSTER_IP=sensors
      - CLUSTER_PORT=2551
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome

  keypad:
    build:
      context: ../
      dockerfile: docker/Dockerfile.keypad
    environment:
      - CLUSTER_IP=keypad
      - CLUSTER_PORT=2552
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome

  alarm:
    build:
      context: ../
      dockerfile: docker/Dockerfile.alarm
    environment:
      - CLUSTER_IP=alarm
      - CLUSTER_PORT=2553
      - SMARTHOME_PORT_1600_TCP_ADDR=smartHome